# Generated by Django 5.2.4 on 2025-07-23 10:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'city')},
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('geo', models.CharField(max_length=255)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video/')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estates', to='Product.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estates', to='Product.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estates', to='Product.district')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='estate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.estate'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
