# Generated by Django 5.2.4 on 2025-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/avatars/')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('role', models.CharField(choices=[('standard_user', 'Standard'), ('manager', 'Manager'), ('accountant', 'Accountant')], default='standard_user', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
