# Generated by Django 5.2.4 on 2025-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_myuser_is_active_myuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
