# Generated by Django 5.2.4 on 2025-07-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_myuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
